### PR TITLE
Show flightplan in the game (work in progress)

### PR DESCRIPTION
**Pull request by jcowgill**
This commit draws the entire flight plan (from the next waypoint) using lines. I've also removed the highlighted waypoint because after this it seems a little pointless.

I'm putting this here since no-one else seemed to want to do it this way.

### CODE REVIEW

**Comment by thisisrobkerry** [comment]
Does this update regularly, i.e. does it remove a line once you've been through a waypoint?

**Comment by jcowgill** [comment]
Yes it does. Here's a screenshot - the orange colour can be changed :)

screenshot from 2014-01-18 19 56 15

**Comment by thisisrobkerry** [comment]
Looks great, you could highlight all the waypoints in the flight plan instead of just the next one?

**Comment by jcowgill** [comment]
Yeah I think that's a good idea. Are we going to be highlighting the entry / exit points at all?

**Comment by thisisrobkerry** [comment]
Potentially, semicircles maybe?—

**Comment by jcowgill** [comment]
The waypoints in the flight plan are now highlighted. It's done by drawing over the red waypoints but I think this looks ok. At the minute the exit point isn't treated specially so it also has a yellow dot.

screenshot from 2014-01-18 20 17 57

**Comment by thisisrobkerry** [comment]
That looks great, could you set it so entry/exits use a different texture that we can change later?—

**Comment by jcowgill** [comment]
OK I've changed the exit points to use the circle textures used for selecting aircraft.

screenshot from 2014-01-18 20 37 20

**Comment by thisisrobkerry** [comment]
Nice, we can sort something else at some point!

**Comment by jk1993** [comment]
Looks really good

**Pull request merged**
